### PR TITLE
Undefined map method causes crash when running repl.

### PR DESCRIPTION
**Pull request by Shearerbeard**
When running TSUN in repl mode the map method chained to the get getNamedDeclarations call throws a fatal exception. I swapped this out for an imparative for loop and it seems to have solved the problem as the collection returned from this call doesn't appear to be a true array. Running node v0.12.2 on OS X 10.10.

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
Thanks for your pull request! I will look into it a bit more, it seems like TypeScript's compiler has been upgraded so that `getNamedDeclarations` are no longer an array.

**Comment by HerringtonDarkholme** [comment]
I'm so sorry that after updating to TypeScript1.5-beta, `getNamedDeclarations` are no longer a method on `SourceFile`. So we need to update more than changing `map`.

**Comment by Shearerbeard** [comment]
Okay, I hadn't bumped the version on my end yet but I may give it a try
this weekend - I've spent a little time with the compiler working on some
script loaders so maybe I'll get lucky and track it down.

**Comment by HerringtonDarkholme** [comment]
Keeping TS compiler updated is the uttermost goal of tsun. If we cannot `getDeclarations` from `SourceFile`, I think we would have to discard some features.

**Comment by HerringtonDarkholme** [comment]
Please refer to https://github.com/HerringtonDarkholme/typescript-repl/commit/c2e62a37b33a25141e2d84394cbc42e2ed490302

**Comment by Shearerbeard** [comment]
Thanks. Just pulled down fresh code and everything seems to be running fine
after the 1.5 beta upgrades you pushed.

On Fri, May 29, 2015 at 12:02 AM, NoNameSheep notifications@github.com
wrote:

> Please refer to c2e62a3
> https://github.com/HerringtonDarkholme/typescript-repl/commit/c2e62a37b33a25141e2d84394cbc42e2ed490302
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HerringtonDarkholme/typescript-repl/pull/1#issuecomment-106700015
> .

## 

Sent By Shearerbeard

**Pull request closed without merging**
